potions:
  normal: true
  extended: true
  upgraded: true
  splash: true
  lingening: true
  tipped_arrow: true
goat_horn:
  specific: true
dimension:
  nether: true
  end: true
enchanting_table: true
ekalia:
  recipes: true