name: Blocks
version: '${project.version}'
main: fr.mrtayai.blocks.BlockMain
api-version: 1.20
author: MrTayai
commands:
  test:
    description: Affiche le menu test
  test2:
    description: Donne les informations sur l'item qu'on tient
  test3:
    description: Donne les potions pour tester
  color:
    description: Affiche le menu de couleur
  team:
    description: Gestion des équipes
  t:
    description: Permet de parler avec les équipes