name: Blocks
version: '${project.version}'
main: fr.mrtayai.blocks.BlockMain
api-version: "1.20"
author: MrTayai
load: STARTUP
commands:
  base:
    description: Permet de téléporter les joueurs à leur base
  farm:
    description: Permet de téléporter les joueurs à leur farm
  start:
    description: Permet de forcer le démarrage de la partie
    permission: blocks.start
  team:
    description: Gestion des équipes
    permission: blocks.team
  t:
    description: Permet de parler avec les équipes

  status:
    description: Permet de voir l'état de la partie
    permission: blocks.status

  lobby:
    description: Permet de se téléporter au lobby
  coords:
    description: Permet de donner ses coordonnées à ses amis
  join:
    description: Permet d'ajouter un joueur à la partie actuelle
  stop:
    description: Permet d'arrêter la partie
    permission: blocks.stop
  pause:
    description: Mettre en pause la partie
  unpause:
    description: Reprendre une partie arretée
  stopserver:
    description: Remplace la commande /stop
    permission: blocks.stopserver